// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace EscapeChroniclesGameplayTags
{
	// === Input tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	// === Extended Mover tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsWalkGroundSpeedModeActive);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsJogGroundSpeedModeActive);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Mover_IsRunGroundSpeedModeActive);

	// === Movement tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Moving);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Falling);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_InAir);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_NavWalking);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_OnGround);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Crouching);

	// Movement Modes tags
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Walking);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Jogging);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Mode_Running);

	// === Roles tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Prisoner);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Guard);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_NPC);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Role_Player);

	// === Schedule events tags ===

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Bedtime);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_RollCall);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Meal);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Shower);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(ScheduleEvent_Alert);

	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_CheckedIn);
	ESCAPECHRONICLES_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Wanted);
}